### ISSUE TITLE
💄 Design: 전체화면 Typo 적용

### ISSUE THREAD

**Issue by Wlfjd** [eco-dessert-platform/dessert-front#336]
### ✨ 작업 내용

- 전체화면 Typo 적용

### ⚙ 상세한 작업 내용

- [ ] : 전체화면 Typo 적용

### 🛠 예상 소요시간

하루 이상

**Comment by hyejinny97** [comment]
메인 스토어 목록 페이지랑 메인 스토어 상세 페이지 Typo 수정은 제가 하겠습니다!
